browserType='Chrome'
address ='https://outbound.ynt.ai/outplan/index.html#/login'
account ='gurr@kalamodo.com'
password ='ynt123'
Report_path='report\\'
cases_path='src\\testCases\\'
title='外呼计划UI层测试报告'
description='测试情况'
Driver='driver\\chromedriver.exe'
e_account="//input[@placeholder='请输入邮箱账号']"
e_password="//input[@type='password']"
e_login_button="//span[text()='立即登录']"
e_updateGroup="//div[@class='caTitle']/i"
e_phoneNumManage="//span[text()='客户管理']"
e_addGroup="//span[text()='添加分组']"
e_inputName="//input[@placeholder='输入名称']"
e_commit="//i[@title='确定']"
e_deleteGroup="//span[text()='%var%']/ancestor::li"
e_deleteCommit="//span[text()='%var%']/ancestor::li/div/i[@title='删除']"
e_ok="//div[@class='ivu-modal-confirm']/div[3]/button[2]/span"
e_closeCusGroup="//div[text()='客户分组']/ancestor::div[@class='ivu-modal-content']/a"
groupName='自动化测试'
e_personalDetails="//div[contains(text(),'gurr@kalamodo.com')]"
e_sip="//li/span[contains(text(),'线路管理')]"
e_addButton="//button[@class='ivu-btn ivu-btn-primary']"
e_ownSip="//li[text()='自有线路']"
e_industryType="//div[@class='vue-treeselect__control-arrow-container']"
e_financial="//label[contains(text(),'金融类')]"
e_education="//label[contains(text(),'教育类')]"
e_sipText="//input[@placeholder='请输入SIP账号']"
e_sipPassword="//input[@placeholder='请输入SIP密码']"
e_ipText="//input[@placeholder='请输入IP']"
e_portText="//input[@placeholder='请输入端口']"
e_locationSelectText="//input[@placeholder='请选择']"
e_city="//ul[@class='ivu-cascader-menu']/li[contains(text(),'%var%')]"
e_sipState="//span[@class='ivu-switch ivu-switch-checked ivu-switch-large']"
e_saveButton="//button[@class='mr60 ivu-btn ivu-btn-primary']"
sipAccount='17100001888'
number='17100001888'
sipPassword='yntst123'
sipIp='114.67.90.115'
sipPort='8060'
city='北京'
e_updateSip="//span[text()='%var%']/ancestor::td[@class='ivu-table-hidden']/preceding-sibling::td/div/div/span[text()='%edit%']"
e_ensure="//span[text()='确定']"
e_assertSip="//span[text()='%var%']"
e_outPlanMenu="//span[text()='外呼计划']"
e_createPlan="//span[text()='创建外呼']"
e_planName="//input[@placeholder='不超过30个字符']"
planName='autoTest'
e_selectScene="//span[text()='请选择呼叫场景']"
e_sceneName="//li[text()='%var%']"
sceneName='尚德墨丘利-副本'
e_callType="//span[text()='%var%']"
e_selectSip="//span[text()='%var%']"
e_addSip="//span[text()='%var%']/ancestor::tr/td[1]/div/label/span/input"
e_allSelectSip="//span[text()='sip名称']/ancestor::tr/th[1]/div/label/span/input"
e_group="//label[text()='选择客户组']/self::label/span/input"
e_down="//div[text()='新建计划']/ancestor::div[@class='ivu-modal-content']/div[2]/form/div[12]/div"
e_importNumber="//a[contains(text(),'导入号码')]"
e_manuallyAdd="//li[text()='手动添加']"
e_selectExistingGroup="//div[text()='手动添加号码']/ancestor::div[@class='ivu-modal-content']/div[2]/form/div/div/div/label[2]/span/input"
e_selectGroup="//label[text()='添加至']/parent::div/div/div/div/div[3]"
e_all="//label[contains(text(),'%var%')]"
e_numberText="//textarea[@placeholder='请输入号码']"
e_closePrompt="//div[text()='提示']/ancestor::div[@class='ivu-modal-content']/a/i"
e_checkGroup="//span[text()='%var%']/ancestor::tbody[@class='ivu-table-tbody']/tr[3]/td[1]/div/label/span/input"
e_closeSuccessPlan="//span[contains(text(),'新建外呼任务成功！')]/ancestor::div[@class='ivu-modal-content']/a"
e_planSuspended="//p[text()='%var%']/ancestor::div[@class='cardTitle']/p/span[text()='已暂停']"
e_planOngoing="//p[text()='qweqe']/ancestor::div[@class='cardTitle']/p/span/span[text()='进行中']"
e_end="//p[text()='%var%']/ancestor::div[@class='card active']/div[3]/div/span[text()='结束']"
e_endEnsure="//div[text()='提示']/ancestor::div[@class='ivu-modal-confirm']/div[3]/button/span[text()='确定']"
e_plan="//p[text()='%var%']/ancestor::div[@class='card active']"
e_x="//div[text()='x']"
e_finish="//p[text()='%var%']/ancestor::div[@class='cardTitle']/p/span[text()='已结束']"
e_x_ensure="//div[text()='提示']/ancestor::div[@class='ivu-modal-confirm']/div[3]/button[2]/span[text()='确定']"
e_moveAccount="//div[contains(text(),'%var%')]"
e_loginOut="//i[text()='退出']"
e_intoScene="//span[text()='话术中心']"
e_sceneManage="//span[text()='话术配置']"
e_textVersion="//span[text()='测试版本']"
e_createScene="//span[text()='新建场景']"
e_scene_Name="//label[text()='场景名称']/following-sibling::div[@class='ivu-form-item-content']/div/input"
e_businessType="//input[@placeholder='行业类型']"
e_type_financial="//li[contains(text(),'金融类')]"
e_loans="//li[contains(text(),'贷款')]"
e_scene="//p[contains(text(),'%var%')]"
e_deleteScene="//p[contains(text(),'%var%')]//ancestor::div[@class='ivu-card-body']/i"
e_edit="//p[contains(text(),'%var%')]/parent::div/p[4]/button/span[text()='编辑']"
e_scene_flow="//div[contains(text(),'场景流程')]"
e_mainProcess="//label[contains(text(),'主流程')]"
e_addQuestion="//span[text()='添加问答']"
e_triggerCondition="//span[text()='自然顺序']"
e_selectNatural="//li[text()='自然顺序']"
e_selectOther="//li[text()='命中其他问答的预设回答结果']"
e_processName="//input[@placeholder='请填写本轮流程描述，方便辨识，不超过10个字']"
name1_1='开场语'
e_wordDetils="//textarea[@placeholder='请填写合成语音内容,不超过400个字...']"
name1_2='喂，您好，我这边是优蓝网的客服专员，您之前有浏览过我们的招聘信息，您还记得吗？'
e_sure="//label[contains(text(),'肯定')]/self::label/span"
e_negate="//label[contains(text(),'否定')]/self::label/span"
e_otherWay="//div[contains(text(),'其他方式')]"
e_syntheticVoice="//div[text()='合成语音']"
e_backupwords="//div[text()='+添加备用话术']"
e_submit="//span[text()='提交']"
e_endWord="//span[text()='添加结束语']"
e_endWordName="//input[@placeholder='填写本轮结束语的名称，方便辨识即可']"
e_artificialService="//span[text()='添加转人工']"
e_addTriggerAnswer="//span[text()='添加触发问答']"
e_trigger_answer1_1="//label[text()='%var%']/parent::div/div/div[1]"
e_trigger_answer1_2="//label[text()='%var%']/parent::div/div/div[2]"
e_job="//li[text()='%var%']"
e_answer2="//label[text()='触发问答2']/parent::div/div/div/div[2]/ul[2]/li[text()='%var%'][1]"
name2_1="工作的打算"
name2_2="是这样的，给您来电主要是想了解一下，您接下来有没有找工作的打算呢？"
name3_1='挽留语1'
name3_2='呃这样啊，我们优蓝网全国免费找工作，可以通过工资、福利排名为您推荐最合适的企业。您近期有换工作的想法吗？'
name4_1='加微信'
name4_2='那要不这样，您手机号码可以加微信么？我加您下，方便您后期想要联系的时候能够及时找到我。'
name5_1='结束语1'
name5_2='好的，那我这边就不打扰您了，祝您生活愉快，再见。'
name6_1='工作类型询问'
name6_2='呃是这样的。我们优蓝网可以全国免费找工作，您想找什么类型的工作呢？'
name7_1='工作地点询问'
name7_2='好的，那您想在哪个城市找工作呢？'
name8_1='安排顾问'
name8_2='好的，我了解了，那一会我给您安排一个专属的求职顾问，他会根据你的情况和期望，帮你推荐最合适的企业，您看可以吗？'
name10_1='结束语1'
name11_1='结束语2'
name11_2='好的，那稍后您注意接听一下优蓝95开头的来电号码，您的专属求职顾问会和您进行深入探讨，祝您生活愉快，再见！'
nameList=[name1_1,name1_2,name2_1,name2_2,name3_1,name3_2,name4_1,name4_2,name5_1,name5_2,name6_1,name6_2,name7_1,name7_2,name8_1,name8_2,name10_1,name11_1,name11_2]